/**
 * Dictionnaire des codes NAF rev. 2 (INSEE) vers leur libellé court.
 *
 * Source : nomenclature d'activités française rev. 2, INSEE (publique).
 * Liste centrée sur les secteurs les plus fréquents en France métropolitaine
 * (construction, commerce, services, industrie, éducation, IT, santé…).
 *
 * Format des clés : code à 5 caractères avec ou sans le point (ex : "43.91A"
 * ou "4391A"). On normalise la clé à la recherche.
 */

const NAF_LABELS_RAW: Record<string, string> = {
  // ---------- Agriculture, sylviculture et pêche ----------
  "0111Z": "Culture de céréales",
  "0113Z": "Culture de légumes, melons, racines et tubercules",
  "0119Z": "Autres cultures non permanentes",
  "0121Z": "Culture de la vigne",
  "0125Z": "Culture d'autres fruits",
  "0141Z": "Élevage de vaches laitières",
  "0142Z": "Élevage d'autres bovins et de buffles",
  "0143Z": "Élevage de chevaux et d'autres équidés",
  "0145Z": "Élevage d'ovins et de caprins",
  "0146Z": "Élevage de porcins",
  "0147Z": "Élevage de volailles",
  "0150Z": "Culture et élevage associés",
  "0210Z": "Sylviculture et autres activités forestières",
  "0220Z": "Exploitation forestière",
  "0312Z": "Pêche en eau douce",

  // ---------- Industries extractives ----------
  "0811Z": "Extraction de pierres ornementales et de construction",
  "0812Z": "Exploitation de gravières et sablières",

  // ---------- Industrie agro-alimentaire ----------
  "1011Z": "Transformation et conservation de la viande de boucherie",
  "1013A": "Préparation industrielle de produits à base de viande",
  "1013B": "Charcuterie",
  "1051A": "Fabrication de lait liquide et de produits frais",
  "1052Z": "Fabrication de glaces et sorbets",
  "1071A": "Fabrication industrielle de pain et pâtisserie fraîche",
  "1071B": "Cuisson de produits de boulangerie",
  "1071C": "Boulangerie et boulangerie-pâtisserie",
  "1071D": "Pâtisserie",
  "1101Z": "Production de boissons alcooliques distillées",
  "1102A": "Fabrication de vins effervescents",
  "1102B": "Vinification",
  "1105Z": "Fabrication de bière",
  "1107A": "Industrie des eaux de table",

  // ---------- Industrie manufacturière diverse ----------
  "1392Z": "Fabrication d'articles textiles, sauf habillement",
  "1610A": "Sciage et rabotage du bois",
  "1812Z": "Autre imprimerie (labeur)",
  "1813Z": "Activités de pré-presse",
  "2042Z": "Fabrication de parfums et de produits pour la toilette",
  "2120Z": "Fabrication de préparations pharmaceutiques",
  "2229A": "Fabrication de pièces techniques en plastique",
  "2511Z": "Fabrication de structures métalliques et de leurs parties",
  "2562B": "Mécanique industrielle",
  "2599A": "Fabrication d'articles métalliques ménagers",
  "2620Z": "Fabrication d'ordinateurs et d'équipements périphériques",
  "2670Z": "Fabrication de matériels optique et photographique",
  "2811Z": "Fabrication de moteurs et turbines",
  "3101Z": "Fabrication de meubles de bureau et de magasin",
  "3102Z": "Fabrication de meubles de cuisine",
  "3109A": "Fabrication de sièges d'ameublement d'intérieur",
  "3109B": "Fabrication d'autres meubles et industries connexes",

  // ---------- Production et distribution d'énergie ----------
  "3511Z": "Production d'électricité",
  "3514Z": "Commerce d'électricité",
  "3811Z": "Collecte des déchets non dangereux",

  // ---------- Construction ----------
  "4110A": "Promotion immobilière de logements",
  "4110B": "Promotion immobilière de bureaux",
  "4110C": "Promotion immobilière d'autres bâtiments",
  "4120A": "Construction de maisons individuelles",
  "4120B": "Construction d'autres bâtiments",
  "4211Z": "Construction de routes et autoroutes",
  "4221Z": "Construction de réseaux pour fluides",
  "4291Z": "Construction d'ouvrages maritimes et fluviaux",
  "4299Z": "Construction d'autres ouvrages de génie civil n.c.a.",
  "4311Z": "Travaux de démolition",
  "4312A": "Travaux de terrassement courants et travaux préparatoires",
  "4312B": "Travaux de terrassement spécialisés ou de grande masse",
  "4321A": "Travaux d'installation électrique dans tous locaux",
  "4321B": "Travaux d'installation électrique sur la voie publique",
  "4322A": "Travaux d'installation d'eau et de gaz en tous locaux",
  "4322B": "Travaux d'installation d'équipements thermiques et de climatisation",
  "4329A": "Travaux d'isolation",
  "4329B": "Autres travaux d'installation n.c.a.",
  "4331Z": "Travaux de plâtrerie",
  "4332A": "Travaux de menuiserie bois et PVC",
  "4332B": "Travaux de menuiserie métallique et serrurerie",
  "4332C": "Agencement de lieux de vente",
  "4333Z": "Travaux de revêtement des sols et des murs",
  "4334Z": "Travaux de peinture et vitrerie",
  "4339Z": "Autres travaux de finition",
  "4391A": "Travaux de charpente",
  "4391B": "Travaux de couverture par éléments",
  "4399A": "Travaux d'étanchéification",
  "4399B": "Travaux de montage de structures métalliques",
  "4399C": "Travaux de maçonnerie générale et gros œuvre de bâtiment",
  "4399D": "Autres travaux spécialisés de construction",
  "4399E": "Location avec opérateur de matériel de construction",

  // ---------- Commerce ; réparation d'automobiles ----------
  "4511Z": "Commerce de voitures et de véhicules automobiles légers",
  "4519Z": "Commerce d'autres véhicules automobiles",
  "4520A": "Entretien et réparation de véhicules automobiles légers",
  "4520B": "Entretien et réparation d'autres véhicules automobiles",
  "4531Z": "Commerce de gros d'équipements automobiles",
  "4532Z": "Commerce de détail d'équipements automobiles",
  "4540Z": "Commerce et réparation de motocycles",
  "4621Z": "Commerce de gros de céréales et d'aliments pour animaux",
  "4631Z": "Commerce de gros de fruits et légumes",
  "4634Z": "Commerce de gros de boissons",
  "4639A": "Commerce de gros alimentaire spécialisé divers",
  "4639B": "Commerce de gros alimentaire non spécialisé",
  "4641Z": "Commerce de gros de textiles",
  "4642Z": "Commerce de gros d'habillement et de chaussures",
  "4643Z": "Commerce de gros d'appareils électroménagers",
  "4651Z": "Commerce de gros d'ordinateurs, équipements informatiques",
  "4652Z": "Commerce de gros de composants et d'équipements électroniques",
  "4669A": "Commerce de gros de matériel électrique",
  "4673A": "Commerce de gros de bois et de matériaux de construction",
  "4673B": "Commerce de gros d'appareils sanitaires et de produits de décoration",
  "4674A": "Commerce de gros de quincaillerie",
  "4711B": "Commerce d'alimentation générale",
  "4711C": "Supérettes",
  "4711D": "Supermarchés",
  "4711F": "Hypermarchés",
  "4719B": "Autres commerces de détail en magasin non spécialisé",
  "4721Z": "Commerce de détail de fruits et légumes en magasin spécialisé",
  "4722Z": "Commerce de détail de viandes et de produits à base de viande",
  "4724Z": "Commerce de détail de pain, pâtisserie et confiserie",
  "4725Z": "Commerce de détail de boissons en magasin spécialisé",
  "4730Z": "Commerce de détail de carburants en magasin spécialisé",
  "4741Z": "Commerce de détail d'ordinateurs, périphériques et logiciels",
  "4742Z": "Commerce de détail de matériels de télécommunication",
  "4751Z": "Commerce de détail de textiles en magasin spécialisé",
  "4752A": "Commerce de détail de quincaillerie, peintures et verres",
  "4752B": "Commerce de détail de matériaux de construction",
  "4759A": "Commerce de détail de meubles",
  "4759B": "Commerce de détail d'appareils électroménagers",
  "4761Z": "Commerce de détail de livres en magasin spécialisé",
  "4771Z": "Commerce de détail d'habillement en magasin spécialisé",
  "4772A": "Commerce de détail de la chaussure",
  "4772B": "Commerce de détail de maroquinerie et d'articles de voyage",
  "4773Z": "Commerce de détail de produits pharmaceutiques",
  "4774Z": "Commerce de détail d'articles médicaux et orthopédiques",
  "4775Z": "Commerce de détail de parfumerie et de produits de beauté",
  "4776Z": "Commerce de détail de fleurs, plantes et animaux de compagnie",
  "4778A": "Commerces de détail d'optique",
  "4778C": "Autres commerces de détail spécialisés divers",
  "4781Z": "Commerce de détail alimentaire sur éventaires et marchés",
  "4789Z": "Autre commerce de détail sur éventaires et marchés",
  "4791A": "Vente à distance sur catalogue général",
  "4791B": "Vente à distance sur catalogue spécialisé",

  // ---------- Transports et entreposage ----------
  "4910Z": "Transport ferroviaire interurbain de voyageurs",
  "4931Z": "Transports urbains et suburbains de voyageurs",
  "4932Z": "Transports de voyageurs par taxis",
  "4939A": "Transports routiers réguliers de voyageurs",
  "4939B": "Autres transports routiers de voyageurs",
  "4941A": "Transports routiers de fret interurbains",
  "4941B": "Transports routiers de fret de proximité",
  "5210A": "Entreposage et stockage frigorifique",
  "5210B": "Entreposage et stockage non frigorifique",
  "5310Z": "Activités de poste dans le cadre d'une obligation de service universel",
  "5320Z": "Autres activités de poste et de courrier",

  // ---------- Hébergement et restauration ----------
  "5510Z": "Hôtels et hébergement similaire",
  "5520Z": "Hébergement touristique et autre hébergement de courte durée",
  "5530Z": "Terrains de camping et parcs pour caravanes ou véhicules de loisirs",
  "5610A": "Restauration traditionnelle",
  "5610B": "Cafétérias et autres libres-services",
  "5610C": "Restauration de type rapide",
  "5621Z": "Services des traiteurs",
  "5629A": "Restauration collective sous contrat",
  "5630Z": "Débits de boissons",

  // ---------- Information et communication ----------
  "5811Z": "Édition de livres",
  "5814Z": "Édition de revues et périodiques",
  "5821Z": "Édition de jeux électroniques",
  "5829A": "Édition de logiciels système et de réseau",
  "5829B": "Édition de logiciels outils de développement et de langages",
  "5829C": "Édition de logiciels applicatifs",
  "6010Z": "Édition et diffusion de programmes radio",
  "6020A": "Édition de chaînes généralistes",
  "6020B": "Édition de chaînes thématiques",
  "6110Z": "Télécommunications filaires",
  "6120Z": "Télécommunications sans fil",
  "6190Z": "Autres activités de télécommunication",
  "6201Z": "Programmation informatique",
  "6202A": "Conseil en systèmes et logiciels informatiques",
  "6202B": "Tierce maintenance de systèmes et d'applications informatiques",
  "6203Z": "Gestion d'installations informatiques",
  "6209Z": "Autres activités informatiques",
  "6311Z": "Traitement de données, hébergement et activités connexes",
  "6312Z": "Portails Internet",

  // ---------- Activités financières et d'assurance ----------
  "6419Z": "Autres intermédiations monétaires",
  "6420Z": "Activités des sociétés holding",
  "6512Z": "Autres assurances",
  "6622Z": "Activités des agents et courtiers d'assurances",

  // ---------- Activités immobilières ----------
  "6810Z": "Activités des marchands de biens immobiliers",
  "6820A": "Location de logements",
  "6820B": "Location de terrains et autres biens immobiliers",
  "6831Z": "Agences immobilières",
  "6832A": "Administration d'immeubles et autres biens immobiliers",
  "6832B": "Supports juridiques de programmes",

  // ---------- Activités spécialisées, scientifiques et techniques ----------
  "6910Z": "Activités juridiques",
  "6920Z": "Activités comptables",
  "7010Z": "Activités des sièges sociaux",
  "7021Z": "Conseil en relations publiques et communication",
  "7022Z": "Conseil pour les affaires et autres conseils de gestion",
  "7111Z": "Activités d'architecture",
  "7112A": "Activité des géomètres",
  "7112B": "Ingénierie, études techniques",
  "7120A": "Contrôle technique automobile",
  "7120B": "Analyses, essais et inspections techniques",
  "7211Z": "Recherche-développement en biotechnologie",
  "7311Z": "Activités des agences de publicité",
  "7320Z": "Études de marché et sondages",
  "7410Z": "Activités spécialisées de design",
  "7420Z": "Activités photographiques",
  "7430Z": "Traduction et interprétation",
  "7490A": "Activité des économistes de la construction",
  "7490B": "Activités spécialisées, scientifiques et techniques diverses",
  "7500Z": "Activités vétérinaires",

  // ---------- Activités de services administratifs et de soutien ----------
  "7711A": "Location de courte durée de voitures et de véhicules automobiles légers",
  "7711B": "Location de longue durée de voitures et de véhicules automobiles légers",
  "7820Z": "Activités des agences de travail temporaire",
  "7830Z": "Autre mise à disposition de ressources humaines",
  "7911Z": "Activités des agences de voyage",
  "7912Z": "Activités des voyagistes",
  "8010Z": "Activités de sécurité privée",
  "8020Z": "Activités liées aux systèmes de sécurité",
  "8110Z": "Activités combinées de soutien lié aux bâtiments",
  "8121Z": "Nettoyage courant des bâtiments",
  "8122Z": "Autres activités de nettoyage des bâtiments et nettoyage industriel",
  "8129A": "Désinfection, désinsectisation, dératisation",
  "8129B": "Autres activités de nettoyage n.c.a.",
  "8130Z": "Services d'aménagement paysager",
  "8211Z": "Services administratifs combinés de bureau",
  "8219Z": "Photocopie, préparation de documents et autres activités de soutien",
  "8220Z": "Activités de centres d'appels",
  "8230Z": "Organisation de salons professionnels et congrès",
  "8292Z": "Activités de conditionnement",
  "8299Z": "Autres activités de soutien aux entreprises n.c.a.",

  // ---------- Administration publique ----------
  "8411Z": "Administration publique générale",

  // ---------- Enseignement ----------
  "8510Z": "Enseignement pré-primaire",
  "8520Z": "Enseignement primaire",
  "8531Z": "Enseignement secondaire général",
  "8532Z": "Enseignement secondaire technique ou professionnel",
  "8541Z": "Enseignement post-secondaire non supérieur",
  "8542Z": "Enseignement supérieur",
  "8551Z": "Enseignement de disciplines sportives et d'activités de loisirs",
  "8552Z": "Enseignement culturel",
  "8553Z": "Enseignement de la conduite",
  "8559A": "Formation continue d'adultes",
  "8559B": "Autres enseignements",
  "8560Z": "Activités de soutien à l'enseignement",

  // ---------- Santé humaine et action sociale ----------
  "8610Z": "Activités hospitalières",
  "8621Z": "Activité des médecins généralistes",
  "8622A": "Activités de radiodiagnostic et de radiothérapie",
  "8622B": "Activités chirurgicales",
  "8622C": "Autres activités des médecins spécialistes",
  "8623Z": "Pratique dentaire",
  "8690A": "Ambulances",
  "8690B": "Laboratoires d'analyses médicales",
  "8690D": "Activités des infirmiers et des sages-femmes",
  "8690E": "Activités des professionnels de la rééducation",
  "8690F": "Activités de santé humaine non classées ailleurs",
  "8710A": "Hébergement médicalisé pour personnes âgées",
  "8710B": "Hébergement médicalisé pour enfants handicapés",
  "8810A": "Aide à domicile",
  "8810B": "Accueil ou accompagnement sans hébergement d'adultes handicapés",
  "8810C": "Aide par le travail",
  "8891A": "Accueil de jeunes enfants",
  "8891B": "Accueil ou accompagnement sans hébergement d'enfants handicapés",
  "8899A": "Autre accueil ou accompagnement sans hébergement d'enfants",
  "8899B": "Action sociale sans hébergement n.c.a.",

  // ---------- Arts, spectacles et activités récréatives ----------
  "9001Z": "Arts du spectacle vivant",
  "9002Z": "Activités de soutien au spectacle vivant",
  "9003A": "Création artistique relevant des arts plastiques",
  "9003B": "Autre création artistique",
  "9004Z": "Gestion de salles de spectacles",
  "9101Z": "Gestion des bibliothèques et des archives",
  "9102Z": "Gestion des musées",
  "9311Z": "Gestion d'installations sportives",
  "9312Z": "Activités de clubs de sports",
  "9313Z": "Activités des centres de culture physique",
  "9319Z": "Autres activités liées au sport",
  "9329Z": "Autres activités récréatives et de loisirs",

  // ---------- Autres activités de services ----------
  "9412Z": "Activités des organisations professionnelles",
  "9499Z": "Autres organisations fonctionnant par adhésion volontaire",
  "9511Z": "Réparation d'ordinateurs et d'équipements périphériques",
  "9521Z": "Réparation de produits électroniques grand public",
  "9522Z": "Réparation d'appareils électroménagers et d'équipements pour la maison et le jardin",
  "9523Z": "Réparation de chaussures et d'articles en cuir",
  "9529Z": "Réparation d'autres biens personnels et domestiques",
  "9601A": "Blanchisserie-teinturerie de gros",
  "9601B": "Blanchisserie-teinturerie de détail",
  "9602A": "Coiffure",
  "9602B": "Soins de beauté",
  "9603Z": "Services funéraires",
  "9604Z": "Entretien corporel",
  "9609Z": "Autres services personnels n.c.a.",
};

/** Normalise un code NAF (suppression du point, mise en majuscules). */
function normalize(code: string): string {
  return code.replace(/\./g, "").toUpperCase().trim();
}

/**
 * Retourne le libellé officiel correspondant au code NAF/APE, ou `null`
 * si le code est inconnu. Accepte les formats "43.91A", "4391A" ou
 * "4391a".
 */
export function getNafLabel(code: string | null | undefined): string | null {
  if (!code) return null;
  const norm = normalize(code);
  return NAF_LABELS_RAW[norm] ?? null;
}
